apiVersion: v1
kind: Service
metadata:
  name: kratos
spec:
  ports:
  - name: http
    port: 4433
    targetPort: 4433
  - name: http-admin
    port: 4434
    targetPort: 4434
  selector:
    app.kubernetes.io/name: kratos
