apiVersion: v1
kind: Secret
metadata:
    name: kratos
    labels:
        app.kubernetes.io/name: kratos
type: Opaque
data:
    # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "kratos") | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}

    secretsDefault: {{ (get $secretData "secretsDefault") | default (randAlphaNum 32 | b64enc) | quote }}
    secretsCookie: {{ (get $secretData "secretsCookie") | default (randAlphaNum 32 | b64enc) | quote }}
    secretsCipher: {{ (get $secretData "secretsCipher") | default (randAlphaNum 32 | b64enc) | quote }}