apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
data:
  initdb.sh: |
    #!/bin/bash

    psql -U ${POSTGRES_USER} <<-END
        CREATE EXTENSION IF NOT EXISTS semver;

        CREATE DATABASE kratos;
        CREATE USER kratos PASSWORD '${KRATOS_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE kratos to kratos;

        \c kratos

        GRANT USAGE, CREATE ON SCHEMA public TO kratos;
    END
